### ISSUE TITLE
YAML:45:25: error: unknown key 'enable-global-analysis'

### ISSUE THREAD

**Issue by michaeleiselsc** [oclint/oclint#406] opened 2017-03-01 03:13 UTC
### Issue Summary
Hi, when using a .oclint file, it doesn't seem to like the line that says "enable-global-analysis: false": https://gist.github.com/michaeleiselsc/30d34582cd407a0e63fc562a7094abbe

### Environment
- Operation system name and version:
OSX 10.11.6, El Capitan
- OCLint version:
LLVM (http://llvm.org/):
  LLVM version 3.9.1
  Optimized build.
  Default target: x86_64-apple-darwin15.6.0
  Host CPU: haswell

OCLint (http://oclint.org/):
  OCLint version 0.11.1.
  Built Jan  8 2017 (11:08:47).
- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?
Homebrew

### Reproduction Steps
Make a small test program, e.g. I made a program test.m with just `int main() {return 0;}` and run with the above .oclint file in the same folder and the command `oclint-json-compilation-database` with the compile_commands.json being `[{"command":"clang test.m","file":"test.m","directory":"/Users/michael/dir"}]`

#### Sample code
`int main() {return 0;}`
Command to run OCLint with the code above.

### Expected Behavior
What do you expect to happen as a result of the reproduction steps?
I expect it to run and do global analysis

### Actual Behavior
What currently happens as a result of the reproduction steps?
I get `YAML:45:25: error: unknown key 'enable-global-analysis'` although I'm not sure if the analysis was global or not

**Comment by UnrealQuester** [comment] 2017-03-01 08:11
I have been unable to reproduce the error given your setup. The only thing I can think of that might cause an issue is some sort of whitespace error in your .oclint file.

Can you create a new `.oclint` file and just copy-paste the contents of your gist into it and see if it still gives you an error?

There is still the possibility that the problem is only in the osx build, in which case someone else would have to confirm they also have this issue on OSX only.

**Comment by vinyldarkscratch** [comment] 2017-03-05 14:13
And it looks like it's my time to shine!  (Well, not really, just confirming the same issue...)

I've been having the same situation on my end (and am also using macOS, installed through Homebrew), where the command line option is just fine, but not the .oclint entry.  I'm currently looking into it, and I found a few arguments weren't able to be controlled by .oclint, enable-global-analysis being one of them.  I've yet to recompile and test, but I would like to ask, @UnrealQuester and @michaeleislsc, where are your .oclint files located?

**Comment by UnrealQuester** [comment] 2017-03-05 16:26
@vinyldarkscratch I have tried to reproduce the issue with a local `.oclint` file in the same directory as the `test.m` file, and with a `.oclint` file in the home directory. Both of these files were parsed by oclint as writing invalid yaml in them caused oclint to emit an error.

**Comment by vinyldarkscratch** [comment] 2017-03-05 19:56
So when you have "enable-global-analysis" in your .oclint files, it doesn't throw any errors?  Hmm, that's strange...  @UnrealQuester, what operating system are you using, and how did you install OCLint?

**Comment by vinyldarkscratch** [comment] 2017-03-06 03:04
Just fixed with #410, hopefully it works for you, @michaeleiselsc?  (I know that one of the two build tests failed, that's just because the main.cpp file doesn't have any tests for it, sorry!)

**Comment by UnrealQuester** [comment] 2017-03-06 07:16
@vinyldarkscratch running on linux and oclint was build from source from commit `327cdc280566ea`.

**Comment by ryuichi-assistant** [comment] 2017-07-13 23:55
There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest version and check if that solves the issue. Let us know if that works for you by adding a comment.

**Comment by ryuichi-assistant** [comment] 2017-08-01 01:59
This issue will be auto-closed because there hasn't been any activity for a few months. Feel free to open a new one if you still experience this problem.

**Closed by ryuichi-assistant** 2017-08-01 01:59 UTC
Labels: ra:waiting-for-reply
