### ISSUE TITLE
Memory Leak when compiler errors occur

### ISSUE THREAD

**Issue by nolange** [oclint/oclint#275] opened 2016-01-08 00:11 UTC
Hello,

oclint has severe issues when the sources cant be compiled. I tested oclint on a codebase of ~500 files, most of which indirectly included a platform-specific header pulling in some arm inline assembly.
the compile_commands.json meanwhile did not include the correct target option for clang, resulting in most of them failing to compile.

Memory for the process use peaked at close to 10GB before oclint finished its run, indicating a rather serious memory leak. A compile_commands.json with the missing --target option added did not use more than 100MB.

Cmdline: /opt/oclint-0.10.2/bin/oclint-json-compilation-database -v -- -disable-rule=LongLine
oclint binary from the official oclint-0.10.2-x86_64-linux-3.13.0-48-generic.tar.gz

PS. you might want to edit your news, at least saying that its not updated and point to github. Project seems dead on the frontpage.

**Comment by ryuichis** [comment] 2016-01-31 21:39
@nolange cc: @UnrealQuester 

Please let us know if the following dev snaphosts fix the issue for you.

https://s3.amazonaws.com/travisci-artifacts.oclint.org/oclint/oclint/24/24.5/build/oclint-0.10.2.dev.1a127a0-x86_64-linux-3.19.0-30-generic.tar.gz

https://s3.amazonaws.com/travisci-artifacts.oclint.org/oclint/oclint/24/24.10/build/oclint-0.10.2.dev.1a127a0-x86_64-darwin-15.0.0.tar.gz

**Comment by UnrealQuester** [comment] 2016-02-05 11:59
I am unable to reproduce the original issue. In my test project (~20 files with compile errors) both versions use the same amount of memory.

**Comment by ryuichis** [comment] 2016-02-06 23:52
I am closing this one since it cannot be reproduced any more. Future observations can be added as a new issue.

**Closed by ryuichis** 2016-02-06 23:52 UTC
