### ISSUE TITLE
Feature request: ignore macros

### ISSUE THREAD

**Issue by michaeleiselsc** [oclint/oclint#405] opened 2017-02-28 21:02 UTC
### Issue Summary
In my code base, there are cases where using macros can lead to odd-looking code when fully unraveled. For example, we have an assert fail macro that, roughly speaking, gets translated from `NSAssertFail("msg")` to `NSAssert(false, "msg")`, which is a standard macro in iOS programming that we have no control over. So these sorts of things would be great to skip.

**Comment by UnrealQuester** [comment] 2017-03-01 07:49
This seems to be a duplicate of #378

**Closed** 2017-03-11 01:02 UTC
