### ISSUE TITLE
xcode8 oclint-json-compilation-database -o generate file Fail Fail Fail Fail

### ISSUE THREAD

**Issue by ChenTF** [oclint/oclint#380] opened 2016-11-16 07:20 UTC
中文:
使用xcodebuild+xcpretty生成compile_commands.json文件, 通过JSON检测工具验证compile_commands.json通过, 但是执行"oclint-json-compilation-database -- -rc=LONG_LINE=200 -rc=NCSS_METHOD=100  -o=oclint.xml"没有生成oclint.xml文件. 
English:
Use the xcodebuild+xcpretty generated compile_commands.json file, By testing the JSON tool to verify compile_commands.json through. but the implementation of "oclint-json-compilation-database ---rc=LONG_LINE=200 -rc=NCSS_METHOD=100 -o=oclint.xml" did not generate the oclint.xml file. 

=====
Bash printing as follows:
bash打印如下:
Running OCLint....20 errors generated.
21 errors generated.
1 error generated.
1 error generated.
24 errors generated.
1 error generated.
1 error generated.
1 error generated.
3 errors generated.
1 error generated.
2 errors generated.
1 error generated.
32 errors generated.
1 error generated.
1 error generated.
20 errors generated.
21 errors generated.
1 error generated.
1 error generated.
24 errors generated.
1 error generated.
...

compile_commands.json file:

[compile_commands.json.zip](https://github.com/oclint/oclint/files/593945/compile_commands.json.zip)

**Comment by shizu2014** [comment] 2016-11-16 07:38
hello

**Comment by UnrealQuester** [comment] 2016-11-16 20:20
What happens if you run the compile commands in the file manually? Do they give you any errors?

**Comment by ChenTF** [comment] 2016-11-17 08:50
@UnrealQuester  没有给出别的错误提示, 就是一串
1 error generated.
24 errors generated.
1 error generated.....

**Comment by ChenTF** [comment] 2016-11-17 09:56
![f3f7cb28-6eab-4fd2-88ad-c3be3e7da8f4](https://cloud.githubusercontent.com/assets/10937460/20384393/971b1cd0-acee-11e6-8716-af4599494ca5.png)

My order of execution is :
1.    rm -rf /Users/chentengfei/Library/Developer/Xcode/DerivedData
2.    xcodebuild clean
3.    xcodebuild -workspace Jiazheng.xcworkspace -scheme Jiazheng -configuration Release CODE_SIGN_IDENTITY="iPhone Distribution: 58 daojia Life Service Co.,Ltd. (SYNJQ6CWNM)"  PRODUCT_BUNDLE_IDENTIFIER="liveHelper" PROVISIONING_PROFILE=4fd21f33-25f8-45d8-962e-e101ed63f3a1 ONLY_ACTIVE_ARCH=NO build | tee xcodebuild.log | xcpretty -r json-compilation-database
4. oclint-json-compilation-database....(Tried many times, type)

**Comment by ChenTF** [comment] 2016-11-17 09:57
@UnrealQuester  Please help .

**Comment by ChenTF** [comment] 2016-11-21 06:00
This question is a personal problem I encountered or a common problem? 
How did you generate OCLint.xml? Before doing what? @UnrealQuester

**Comment by UnrealQuester** [comment] 2016-11-21 14:34
@ChenTF the clang in oclint seems to be unable to compile the code, so no output file can be generated. In the compile_commands.json there are many commands in the form of
```
command: "clang -x objective-c -I/..."
```
Try running these manually and see if they give you any errors.

**Comment by ryuichis** [comment] 2016-11-23 23:21
@ChenTF my first suggestion is the same as @UnrealQuester, please make sure your code can be compiled successfully with the commands you have in your `compile_commands.json` file. 

I am closing this one, and others that do not provide enough information for us to reproduce the issues locally. If this issue still bothers, please share some code so that we have a starting place to dig into.

**Closed by ryuichis** 2016-11-23 23:21 UTC
