### ISSUE TITLE
No such file or directory: '/Library/Developer/CommandLineTools/Toolchains/XcodeDefault.xctoolchain/usr/include/c++'

### ISSUE THREAD

**Issue by FlyingNoob** [oclint/oclint#555] opened 2019-12-18 10:40 UTC
### Issue Summary
oclint 0.15 . build ./make error
### Environment
- Operation system name and version: 10.15.2
- OCLint version: 0.15
- How OCLint is installed: local build? prebuilt binary downloaded from github? homebrew install? others?
github

**Comment by ryuichis** [comment] 2019-12-18 13:49
Duplicate of #552

**Closed by ryuichis** 2019-12-18 13:49 UTC
