### ISSUE TITLE
oclint-json-compilation-database does nothing

### ISSUE THREAD

**Issue by jgatkinsn** [oclint/oclint#257] opened 2015-10-30 19:01 UTC
I'm currently using the 0.8.1 release on ubuntu.  I used "bear" to make my compile_commands.json file, and I'm trying to run the analysis on a set of source code that I can run oclint just fine on individual files.  When I run the oclint-json-compilation-database, it pretty much does nothing. I use the -v option to see and output and all it shows me trying to run oclint with all the files that in the .json file and nothing else.

Here's sample output of the console:

    /opt/oclint-0.8.1/bin/oclint-json-compilation-database  -v -e install -e test
    ------------------------------ OCLint ------------------------------
    /opt/oclint-0.8.1/bin/oclint "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/mock/gpon_control_layer/GclMockedFunctions.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/CmToGclMsg.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GCLOntCapabilityHelper.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/CmToGclMsgQ.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GCLStaticHelperApi.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GCLStaticHelperApiOLT.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclInterface.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclProvisioningInfo.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_CommonStateObject.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_DataServiceDeprovisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_DataServiceProvisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_Ds1ServiceProvisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_EfmDeprovisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_EfmProvisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_MacOuiConfigCmd.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_OmciConfigCmd.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_OnuInitialization.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_PM.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_PotsTest.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_Pwe3ServiceDeprovisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_Pwe3ServiceProvisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_SeltDeltTest.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_ShaperProvisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_VdslDeprovisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_VdslProvisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_VideoServiceDeprovisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_VideoServiceProvisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_VoiceServiceDeprovisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_VoiceServiceProvisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_VoiceSipServiceDeprovisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GclStateMachine_VoiceSipServiceProvisioning.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/GponControlLayer.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/OmciConfigCmd.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/OmciData.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/OmciEthernet.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/OmciIp.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/OmciOntMgmt.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/OmciPwe.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/OmciTcontMgmt.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/OmciVideo.cpp" "/home/jatkinso/ssd_projects/package/gpon_control_layer/main/src/gpon_control_layer/OmciVoip.cpp"
    --------------------------------------------------------------------

**Comment by ryuichis** [comment] 2015-12-27 04:32
@jgatkinsn is this an open source project that I can try to reproduce it locally?

**Comment by ryuichis** [comment] 2016-01-16 19:57
Closing, couldn't reproduce locally.

**Closed by ryuichis** 2016-01-16 19:57 UTC
