### ISSUE TITLE
Cannot disable GotoStatement in .oclint

### ISSUE THREAD

**Issue by brennantaylor** [oclint/oclint#308] opened 2016-03-20 16:50 UTC
I found out that disabling the GotoStatement in the .oclint config file is not having any effect. If I pass `-disable-rule=GotoStatement` then it will work.

We use a library that has some macros that expand into `goto`. We can't remove it just yet so I figured we would just turn the rule off but oclint 0.10.2 doesn't appear to respect that.

```prompt
$ oclint --version
LLVM (http://llvm.org/):
  LLVM version 3.7.0
  Optimized build.
  Built Dec 28 2015 (09:59:04).
  Default target: x86_64-apple-darwin15.3.0
  Host CPU: haswell

OCLint (http://oclint.org/):
  OCLint version 0.10.2.
  Built Dec 28 2015 (10:15:51).
```

**Comment by UnrealQuester** [comment] 2016-03-20 20:08
I am unable to reproduce your issue.

Test file main.cpp
```c++
int main(int argc, char *argv[])
{
    goto err;
err:
    return 0;
}
```
Test file .oclint in the same directory
```yaml
disable-rules:
    - GotoStatement
```
Command line invocation
```bash
oclint main.cpp -- g++
```
Maybe oclint is not picking up your configuration file? Is it just this specific rule or does the issue apply to other rules as well?

**Comment by ryuichis** [comment] 2016-06-18 17:33
Can't reproduce the issue. Closing this one, if this shows up again, a new pull request is welcomed.

**Closed by ryuichis** 2016-06-18 17:33 UTC
