### ISSUE TITLE
oclint-json-compilation-database not running (0.10.2) when analysing iOS project

### ISSUE THREAD

**Issue by leleliu008** [oclint/oclint#312] opened 2016-03-31 06:38 UTC
run command:
oclint-json-compilation-database -e Pods -v -- -report-type pmd -o sonar-reports/oclint.xml

oclint just sits there, with no output (has been like this for over an hour). If I ctrl+c I get this back:

Traceback (most recent call last):
  File "/Users/liufupin/bin/oclint-0.10.2/bin/oclint-json-compilation-database", line 87, in <module>
    exit_code = subprocess.call(oclint_invocation, shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)

**Comment by UnrealQuester** [comment] 2016-04-01 19:43
It looks like the oclint command itself is not returning. Can you check the memory and cpu usage of the oclint process?
How many source files does your project contain?

**Comment by ryuichis** [comment] 2016-11-24 00:03
I have no experience with `sonar`. Based on the limited knowledge the issue is described, I am closing this one.

**Closed by ryuichis** 2016-11-24 00:03 UTC

**Comment by vicwan** [comment] 2017-07-17 01:37
I am facing the same issue. Has anyone solved it already?
